services:
  db:
    image: postgres:16-alpine
    container_name: plivo_log_db
    environment:
      POSTGRES_USER: plivo
      POSTGRES_PASSWORD: plivo_secret
      POSTGRES_DB: log_analyzer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plivo -d log_analyzer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
